//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialMeasurement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        public long ID { get; set; }
        public long ResultMaterialID { get; set; }
        public long ComponentMaterialID { get; set; }
        public double Weight { get; set; }
        public string WeightUnit { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Material Material1 { get; set; }
    }
}
