//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialMeasurement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedInventory
    {
        public long ID { get; set; }
        public long MaterialID { get; set; }
        public string ParcelCode { get; set; }
        public System.DateTime ImportDate { get; set; }
        public double Quantity { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<double> OriginalQuantity { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
