//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialMeasurement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ImportedInventories = new HashSet<ImportedInventory>();
            this.Material1 = new HashSet<Material>();
            this.MeasurementDetailRecords = new HashSet<MeasurementDetailRecord>();
            this.MeasurementRecords = new HashSet<MeasurementRecord>();
            this.Compositions = new HashSet<Composition>();
            this.Compositions1 = new HashSet<Composition>();
            this.MonthReports = new HashSet<MonthReport>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public int Revision { get; set; }
        public Nullable<long> PatId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ImportedInventory> ImportedInventories { get; set; }
        public virtual ICollection<Material> Material1 { get; set; }
        public virtual Material Material2 { get; set; }
        public virtual ICollection<MeasurementDetailRecord> MeasurementDetailRecords { get; set; }
        public virtual ICollection<MeasurementRecord> MeasurementRecords { get; set; }
        public virtual ICollection<Composition> Compositions { get; set; }
        public virtual ICollection<Composition> Compositions1 { get; set; }
        public virtual ICollection<MonthReport> MonthReports { get; set; }
    }
}
