//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialMeasurement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaterialMeasurementEntities : DbContext
    {
        public MaterialMeasurementEntities()
            : base("name=MaterialMeasurementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImportedInventory> ImportedInventories { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MeasurementDetailRecord> MeasurementDetailRecords { get; set; }
        public virtual DbSet<MeasurementRecord> MeasurementRecords { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<MonthReport> MonthReports { get; set; }
    }
}
