//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialMeasurement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementRecord
    {
        public MeasurementRecord()
        {
            this.MeasurementDetailRecords = new HashSet<MeasurementDetailRecord>();
        }
    
        public long ID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public long ResultMaterialID { get; set; }
        public double Weight { get; set; }
        public string WeightUnit { get; set; }
        public string Description { get; set; }
        public string ParcelCode { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ICollection<MeasurementDetailRecord> MeasurementDetailRecords { get; set; }
    }
}
